# Generated by Django 4.2 on 2023-04-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.CharField(max_length=30)),
                ('mem_name', models.CharField(max_length=30)),
                ('mem_email', models.CharField(max_length=50)),
                ('mem_pw', models.CharField(max_length=100)),
                ('mem_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
